sudo: required

language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"

services:
  - docker

before_install:
  - docker pull koalaman/shellcheck

install:
  - npm install -g npm@latest
  - npm install

script:
  - docker run -v $(pwd):/scripts koalaman/shellcheck ./tasks/test.sh
  - bash ./tasks/test.sh
