sudo: required

language: node_js
node_js:
  - "6"

services:
  - docker

before_install:
  - docker-compose --version
  - docker-compose up -d
  - docker-compose ps

install:
  - yarn

script:
  - npm test
  - docker-compose down
