group: edge

sudo: required

language: node_js
node_js:
  - "6"
  - "7"
  - "8"

services:
  - docker

addons:
  apt:
    packages:
      - shellcheck

install:
  - npm install

script:
  - npm test

matrix:
  fast_finish: true
