group: edge
sudo: required

language: node_js
node_js:
- '8'
- '10'
- '12'

services:
- docker

addons:
  apt:
    packages:
    - shellcheck
    - devscripts
    - jq

install:
- npm install

script:
- npm test

branches:
  only:
  - master
  - v1.x.x

matrix:
  fast_finish: true

before_deploy:
- bash ./tasks/deploy.sh

deploy:
- provider: releases
  api_key:
    secure: "$github_token"
  on:
    repo: sumitgoelpw/zabbix-promise
    branch: master
    node: '8'
- provider: npm
  email: "$npm_email"
  api_key: "npm_token"
  on:
    repo: sumitgoelpw/zabbix-promise
    branch: master
    node: '8'
