version: '2'
services:
  zabbix-database:
      image: postgres:alpine
      environment:
        POSTGRES_USER: ${DBUSER}
        POSTGRES_PASSWORD: ${DBPASS}
  zabbix-server:
      image: zabbix/zabbix-server-pgsql:${ZABTAG}
      environment:
        DB_SERVER_HOST: zabbix-database
        POSTGRES_USER: ${DBUSER}
        POSTGRES_PASSWORD: ${DBPASS}
      depends_on:
        - zabbix-database
  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:${ZABTAG}
    ports:
      - ${HOSTPORT}:80/tcp
    environment:
      ZBX_SERVER_HOST: zabbix-server
      DB_SERVER_HOST: zabbix-database
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPASS}
      TZ: GMT
    depends_on:
      - zabbix-server
      - zabbix-database
