version: '2'
services:
  zabbix-database:
      hostname: zabbix-database.local
      image: postgres:alpine
      environment:
        POSTGRES_USER: ${DBUSER}
        POSTGRES_PASSWORD: ${DBPASS}
  zabbix-server:
      hostname: zabbix-server.local
      image: zabbix/zabbix-server-pgsql:${ZABTAG}
      environment:
        DB_SERVER_HOST: zabbix-database
        POSTGRES_USER: ${DBUSER}
        POSTGRES_PASSWORD: ${DBPASS}
      depends_on:
        - zabbix-database
  zabbix-web:
    hostname: zabbix-web.local
    image: zabbix/zabbix-web-nginx-pgsql:${ZABTAG}
    volumes:
      - ${NGINXDIRSSL}:/etc/ssl/nginx
    ports:
      - 0.0.0.0:${HOSTPORT}:80/tcp
      - 0.0.0.0:${HOSTPORTSSL}:443/tcp
    environment:
      ZBX_SERVER_HOST: zabbix-server
      DB_SERVER_HOST: zabbix-database
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPASS}
      TZ: GMT
    depends_on:
      - zabbix-server
      - zabbix-database
  zabbix-agent1:
    hostname: zabbix-agent1.local
    image: zabbix/zabbix-agent:${ZABTAG}
    environment:
      ZBX_HOSTNAME: zabbix-agent1
      ZBX_SERVER_HOST: zabbix-server
    depends_on:
      - zabbix-server
  zabbix-agent2:
    hostname: zabbix-agent2.local
    image: zabbix/zabbix-agent:${ZABTAG}
    environment:
      ZBX_HOSTNAME: zabbix-agent2
      ZBX_SERVER_HOST: zabbix-server
    depends_on:
      - zabbix-server
  zabbix-agent3:
    hostname: zabbix-agent3.local
    image: zabbix/zabbix-agent:${ZABTAG}
    environment:
      ZBX_HOSTNAME: zabbix-agent3
      ZBX_SERVER_HOST: zabbix-server
    depends_on:
      - zabbix-server
